### PR TITLE
Add method to invert a ColorScheme (inverse of get)

### LINKED ISSUE #10: Feature request: Invert a ColorScheme (inverse of `get`)
Hi! I came across the need to convert a heatmap image to an Array of continuous values, and in the process discovered this cool package. ColorSchemes is *exactly* what I wanted to represent with code the continuous semantics humans put on a heatmap. Thanks!

But in my case, I already had pixels, and I wanted to find out where each pixel lies on the this continuous ColorScheme, rather than the other way around (the functionality provided by `get(cscheme, x)`.

I've done this before in JavaScript via `d3` to create a map legend you can mouse over:
```javascript
var legendScale = d3.scale.log()
      .domain([minValue,maxValue])
      .range([0,legend.width()]);
// ...
$(legend).mousemove(function(e){
  offset = $(this).offset();
  xPos = e.pageX - offset.left;
  value = prettifyNum(parseFloat(legendScale.invert(xPos).toPrecision(2)));
  mouseovertext[0].textContent=value;
});
```

So anyway, this is a Feature Request to be able to do the same thing with ColorScheme.jl! 😸

---------------------------------------------------

I should've checked to see if this functionality already exists somewhere else, or if it's even a thing people would want, but I got carried away and I wrote it myself... I put the functionality in this package here:
https://github.com/NHDaly/ColorSchemesInvert.jl/blob/master/README.ipynb

If this is something people think makes sense, I can open a pull request to merge that functionality into this package. What do you think?

### PR DESCRIPTION
**Pull request by NHDaly**
Fixes #10.

This PR is to add a method which is the inverse of `get(cscheme, x)`.

For now, I've just copied over `invert` from [NHDaly/ColorSchemesInvert.jl](http://github.com/NHDaly/ColorSchemesInvert.jl). For more details see [NHDaly/ColorSchemesInvert.jl/.../README.ipynb](https://github.com/NHDaly/ColorSchemesInvert.jl/blob/master/README.ipynb).

`invert` places a color within a colorscheme, by converting the color to
a value representing its position on the colorscheme's axis.

Put another way, it returns the value in the domain for which its
colorscheme value most closely matches the provided color.

### CODE REVIEW

**Comment by NHDaly** [comment]
This is still a work in progress. I'm not exactly sure how the method should work, but this is a good start. It does what I think it should, although doesn't behave quite like I expected. See: 
https://github.com/NHDaly/ColorSchemesInvert.jl/blob/4e50015b681679d45cf4f7ddf2d929cc63e67849/test/runtests.jl#L41

I'd love to talk it through some with folks! :)

**Comment by NHDaly** [comment]
> You could move the export line from line 5 to line 116.
Oh sure, can do. Thanks. I didn't notice it way down there. Is there no convention on putting the `export`s at the top?

**Comment by NHDaly** [comment]
> I'm wondering whether an alternative to invert would be getinverse, because it doesn't invert some object, rather it 'gets' a value...

Yeah I think that's better. I can't really think of anything better than that. Thanks! I'll make that change too.

**Comment by NHDaly** [comment]
> The style is to use lowercase (“squishcase”, juliacase) rather than camelCase, so this should be convert_to_scheme or something better...

Okay I've changed it to `convert_to_scheme` for now. But actually, I'm not even sure it's worth including in this PR at all.. It was mostly just something fun that occured to me after implementing `getinverse`. I think right now it has some surprising results due to a surprising definition of "similarity" between colors.

`getinverse` is very useful for determing where in a given `ColorScheme` a color lies -- *if it's actually from that colorscheme*, but it has unexpected effects when converting between color schemes. For example, here, one would expect the black-to-white scale to map 1:1 directly to the black-to-red, but this is not actually the case:

screen shot 2018-01-19 at 4 05 10 pm

So anyway, maybe we just remove this function for now?

**Comment by cormullion** [comment]
Let’s merge this, make a release, and take it for a spin... If it proves problematic we can either document its problems or remove it; if it works we can improve the docs... it will all need extensive changes in a few months anyway!

**Pull request merged**
