### PR TITLE
Use Vector instead of StaticArrays

### LINKED ISSUE #42: Use tuples instead of StaticArrays
As @KristofferC just mentioned in #33 we could use a tuple instead of a Vector for colors chemes, and remove the StaticArrays.jl dependency.

Is there any reason colors need to be in a `Vector` ? I (probably wrongly) assumed there was when I added the dependency to StaticArrays.jl to speed up color-scheme indexing. Tuples are cleaner and would improve package load time a lot, and the load time of other packages like Gaston.jl.

I'll write the PR if there is no problem with making the change.

### PR DESCRIPTION
**Pull request by rafaqz**
closes #42 and removes StaticArrays.jl dependency.

Turns out it just needed a `collect` in the `show` methods to get docs passing. `ColorScheme <: AbstractVector` wasn't needed, and introduces a lot of method ambiguities with `get`.

Very large schemes are still regular vectors underneath.

I found a few minor issues with my earlier PR while looking at this, but I'll fix them in another PR.

### CODE REVIEW

**Comment by rafaqz** [comment]
That's an interesting error on nightly:
https://travis-ci.org/github/JuliaGraphics/ColorSchemes.jl/jobs/737477424#L269

Not sure what package is triggering that,

**Comment by cormullion** [comment]
Great job! Thanks, that's awesome.

I ran ColorSchemeTools.jl tests against `https://github.com/rafaqz/ColorSchemes.jl#tuple`, and found a couple of things in ColorSchemeTools/runtests.jl

```
107    tmp = get(ColorSchemes.leonardo, rand(10, 10))
```

is looking for a `getindex(::NTuple{32,ColorTypes.RGB{Float64}}, ::Array{Int64,2})` method. Also

```
94    ColorSchemeTools.sortcolorscheme
```

is looking for a `sort(::NTuple{32,ColorTypes.RGB{Float64}}` method.

If you think it's better to change ColorSchemeTools that's fine - I think ColorSchemes.jl is the more important package...

**Comment by rafaqz** [comment]
Sorry I haven't run it against any other packages yet, still need to do this with Plots.jl and similar as well.

But I'll have a look at ColorSchemesTools.jl in the next week some time.

**Comment by SimonDanisch** [comment]
Shouldn't they all just be `Vector`? I can't think of anything, that would justify the compilation overhead for tuples...
This also shouldn't be that breaking, is it? Do dependencies actually rely on the implementation detail of using SVector?

**Comment by SimonDanisch** [comment]
Ah I guess precompile files :D  
Anyways, I think this is a pretty important change - if I can help with anything, let me know

**Comment by rafaqz** [comment]
Sorry I completely forgot about this PR. I think you might be right.

They were all vectors previously, but StaticArrays were faster when colourschemes were sampled really heavily in DynamicGrids.jl, which led me to change it. Although I wasn't really thinking about compile time then, just maximizing performance at any cost like a complete newb. I probably made a bad decision. 

Much bigger performance improvements came from fixing instabilities here in the same original PR and later in Colors.jl. I think the Vector/Tuple difference was less important. We could just revert this to Vectors. Or maybe do better benchmarks of the differences in compile time and performance for both options? I'll have a look.

There was a trivial dependency on `AbstractArray` for something somewhere that I didn't understand, that meant I used StaticArray instead of `Tuple`.

**Comment by SimonDanisch** [comment]
> just maximizing performance at any cost like a complete newb

Hehe... 
I think if that's really the case, which I find surprising since indexing performance is usually in the same ballpark for SVector vs Array, that package should just cast the `Vector` to an `SVector`...
Maybe the difference is, that indexing with SVector uses `@inbounds` in more places?

**Comment by rafaqz** [comment]
Yeah maybe inbounds and that in some known cases the compiler just inserts the values at compile time. Or something. I remember having some benchmarks that were faster anyway. But that's a long time ago now and my understanding of Julia was kinda limited.

I'll revert it to `Vector` :)

**Comment by SimonDanisch** [comment]
Awesome! I also don't think we need to be overly concerned with breakage, when we tag a new breaking version ;) Any dependant should then be able to update whenever they can.

**Comment by rafaqz** [comment]
ColorSchemeTools.jl is fine with this too.

**Review by SimonDanisch — APPROVED** [review]

**Comment by rafaqz** [comment]
Also is a minor version bump fine for this? bumping to 4.0 seems drastic. Idk

**Comment by SimonDanisch** [comment]
Sounds fine to me ;) At least Makie doesn't actually break, as far as I can tell!

**Comment by rafaqz** [comment]
I'm not actually sure how semantic versioning extends to the exact types of return values. What should this be technically?

**Pull request merged**
