### PR TITLE
add color pallete by Matthew A. Petroff

### PR DESCRIPTION
**Pull request by Moelf**

### CODE REVIEW

**Comment by cormullion** [comment]
Nice, thanks! Do you want to settle for the names `mpetroff_6` now or are more interesting names coming?

**Comment by Moelf** [comment]
We can wait a bit to see if author responds or what matplotlib settles with

**Comment by cormullion** [comment]
I see the name might change .... 

https://github.com/mpetroff/accessible-color-cycles/issues/1

**Comment by Moelf** [comment]
we don't have to use the same naming I suppose?

we have `mpetroff_6` which is spiritually similar to `petroff6` in that discussion

**Comment by cormullion** [comment]
Yes, it's probably OK as it is, if the names are similar enough.

**Pull request merged**
