### PR TITLE
Add `cividis` colormap

### PR DESCRIPTION
**Pull request by t-bltg**
Adds support for `cividis` colormap from https://github.com/marcosci/cividis under [MIT](https://github.com/marcosci/cividis/blob/2ab965f946116d5ff7b415316dce30312c09de9c/DESCRIPTION#L15) licensing.

### CODE REVIEW

**Comment by cormullion** [comment]
Hi! The reason `cividis` isn't in is because it was already in PlotUtils and Makie, etc.. I'm guessing there won't be any problems in duplicating the colorscheme here as well, but it would be great if you could test your fork against Plots etc to check that there isn't a clash at any stage....

**Comment by t-bltg** [comment]
Hum, `Plots` uses [`ColorSchemes`](https://docs.juliaplots.org/stable/colorschemes/), `:cividis` got introduced in https://github.com/JuliaPlots/PlotUtils.jl/pull/87, with no mention why it was added there and not in `ColorSchemes`, the table should be removed if introduced here.

I've tested this PR with `(@v1.7) pkg> test Plots` and `(@v1.7) pkg> test Makie` without issues.

I'll need this for https://github.com/JuliaPlots/UnicodePlots.jl/pull/272.

**Comment by cormullion** [comment]
Cool, thanks! I'll make a release today or tomorrow...

**Comment by cormullion** [comment]
by the way - will I need to update [this](https://juliagraphics.github.io/ColorSchemes.jl/stable/plotting/#UnicodePlots.jl) when your UnicodePlots updates are done?

**Comment by t-bltg** [comment]
No, providing a `Vector` of `RGB` tuples will still supported.

By the way, `savefig(p, "name.png")` is supported sine `UnicodePlots` `2.10` ;)

```julia
using ColorSchemes, UnicodePlots
z = rand(50, 100)
p = heatmap(z; title = "Hot!", colormap = map(x -> (x.r, x.g, x.b), ColorSchemes.leonardo.colors)
savefig(p, "hot.png"; transparent = false)
```
hot

**Comment by cormullion** [comment]
Cool, thanks. UnicodePlots remains awesome 😀

**Pull request merged**
