### PR TITLE
:zap: New colorschemes based on Julia colors.

### PR DESCRIPTION
**Pull request by davibarreira**
@cormullion we meet again! :grin: 

I didn't see any color schemes based on Julia's colors. So here is a PR with a proposal of color schemes based on Juila. If you find the color schemes redundant, feel free to reject the PR.

### CODE REVIEW

**Review by cormullion — CHANGES_REQUESTED** [review]
Hi Davi. This looks cool, thanks!  

You'll need to remove the stray semicolons.

What's the thinking behind the `:jyellow` and `:jgray`?

**Comment by davibarreira** [comment]
> Hi Davi. This looks cool, thanks!
> 
> You'll need to remove the stray semicolons.
> 
> What's the thinking behind the `:jyellow` and `:jgray`?
The yellow and gray are just extra colors to the regular Julia color scheme that I felt complemented the original palette. I mean, having only 4 colors might be too little for some plots, and I felt that the yellow and the gray matched the original Julia colors.

But feel free to remove them! They were just a non-canonical extra.

**Comment by davibarreira** [comment]
About the color gradations (jblue, jred, etc). They are a variation in 10% of the colors.

**Comment by davibarreira** [comment]
Forgot to add the legacy colors. These are the colors from the original logo :)

**Comment by cormullion** [comment]
That's great! Thanks so much! :) 

Loose ends: 

- Updating the docs usually is just a question of adding another couple of lines to the MD. 

-  CHANGLOG needs updating at some point

**Pull request merged**
