### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by rafaqz**
This PR fixes type stability issues, and uses StaticArrays for colorschemes. I'm getting over an order of magnitude performance improvement displaying live simulations with colorschemes.

### CODE REVIEW

**Comment by cormullion** [comment]
Looks awesome! 

Travis complains about this:

```
ERROR: LoadError: InitError: Evaluation into the closed module `ColorTypes` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `ColorTypes` with `include` during precompilation - don't do this.
```

Is this caused by something here>

**Comment by KristofferC** [comment]
What's the advantage of StaticArrays over using a tuple? Do you need to do math on the vector?

**Comment by rafaqz** [comment]
I used static arrays so as to not change the interface too much in the PR, not knowing why they were vectors in the first place or what the other use cases are. I'm fine with them being tuples, StaticArrays.jl is a bit too heavy a dependency really.

**Comment by rafaqz** [comment]
Is this for Gaston.jl load times? lets swap to tuples.

**Comment by KristofferC** [comment]
> Is this for Gaston.jl load times?

Yes, at least that's why I looked at the load time for this package.

**Pull request merged**
