### PR TITLE
Fix for #17

### PR DESCRIPTION
**Pull request by tlienart**
Simplified the code around `get` a little bit and fixed the issue #17 . Tests pass.

### CODE REVIEW

**Comment by cormullion** [comment]
Hi Thibaut! Thanks for doing this, really helpful.

I'm trying to check this version out, but it's not working for me. (I think I've added your version of the package correctly).

```
julia-1.0> using ColorSchemes

julia-1.0> get(ColorSchemes.leonardo, .2)
ERROR: MethodError: no method matching get(::Array{ColorTypes.RGB{Float64},1}, ::Float64)
Closest candidates are:
  get(::REPL.Terminals.TTYTerminal, ::Any, ::Any) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/REPL/src/Terminals.jl:176
  get(::AbstractArray, ::Integer, ::Any) at abstractarray.jl:1146
  get(::AbstractArray, ::Tuple{}, ::Any) at abstractarray.jl:1147
  ...
Stacktrace:
 [1] top-level scope at none:0
```

Is the basic `get(cscheme, x)` version no longer available? On the released version, there's:

```
julia-1.0> @show get(ColorSchemes.leonardo, .2)
get(ColorSchemes.leonardo, 0.2) = RGB{Float64}(0.17442110750186593,0.10479916072572365,0.07055654401306825)
```

**Comment by tlienart** [comment]
Ha damn! I know exactly what the problem is, small fix needed, will do that asap (and I'll add a test for this, it should have shown!)

**Comment by cormullion** [comment]
Yes, the tests are pretty shabby, really... This package is one of those that was thrown together quickly in the heat of the moment and has never been re-examined with a more sober eye... :)

**Comment by tlienart** [comment]
Ok this fixes it, so I guess the main changes I've done is to make it explicit what `x` could be in the `get` call. It has to be reasonably explicit to avoid ambiguities with `Base.get` when using ranges.

Now it accepts `x` as

* a `<:Real`
* a `Array{<:Real}`
* a `AbstractRange{<:Real}`

Note that even though `AbstractArray` is a supertype for `AbstractRange`, I was not able to just specify `AbstractArray` without triggering the ambiguity with `Base`. 

I've added a test specifically for the example you mention. 

```julia-repl
julia> using ColorSchemes

julia> get(ColorSchemes.leonardo, 0.2)
RGB{Float64}(0.17442110750186593,0.10479916072572365,0.07055654401306825)

julia> get(ColorSchemes.leonardo, [0.2, 0.3])
2-element Array{RGB{Float64},1} with eltype ColorTypes.RGB{Float64}:
 RGB{Float64}(0.17442110750186593,0.10479916072572365,0.07055654401306825)
 RGB{Float64}(0.22591906154344019,0.16479573270952488,0.07789492796643352)

julia> get(ColorSchemes.leonardo, [0.2  0.3; 0.2 0.3])
2×2 Array{RGB{Float64},2} with eltype ColorTypes.RGB{Float64}:
 RGB{Float64}(0.174421,0.104799,0.0705565)  …  RGB{Float64}(0.225919,0.164796,0.0778949)
 RGB{Float64}(0.174421,0.104799,0.0705565)     RGB{Float64}(0.225919,0.164796,0.0778949)

julia> get(ColorSchemes.leonardo, 1:5)
5-element Array{RGB{Float64},1} with eltype ColorTypes.RGB{Float64}:
 RGB{Float64}(0.9724409077178674,0.7907008712807734,0.2851364857083522)
 RGB{Float64}(0.9724409077178674,0.7907008712807734,0.2851364857083522)
 RGB{Float64}(0.9724409077178674,0.7907008712807734,0.2851364857083522)
 RGB{Float64}(0.9724409077178674,0.7907008712807734,0.2851364857083522)
 RGB{Float64}(0.9724409077178674,0.7907008712807734,0.2851364857083522)
```

Is there any other type that you think should be added?

**Comment by cormullion** [comment]
Thanks so much for doing this! I think `get(scheme...)` is pretty versatile now. I've thrashed this a bit so I reckon it's good to go.

**Pull request merged**
